name: Create PDF ebook
on:
  push:
    branches:
      - master

jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Copy script
        run: |
          cp ebook.sh ./hacker-laws/ebook.sh
          
      - name: Fix ebook
        run: sh ebook.sh
        working-directory: ./hacker-laws
          
      - name: Create PDF
        uses: docker://pandoc/latex:latest
        working-directory: ./hacker-laws
        with:
          args: >-
          -V
          toc-title:"Table Of Contents"
          --toc
          --pdf-engine=pdflatex
          -s
          -o
          hacker-laws.pdf
          hacker-laws.md"
          
      - name: Upload created PDF
        uses: actions/upload-artifact@v2
        working-directory: ./hacker-laws
        with:
          name: hacker-laws PDF
          path: hacker-laws.pdf