name: Create PDF ebook
on:
  push:
    branches:
      - master

jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Copy README
        run: cp ./hacker-laws/README.md README.md
          
      - name: Fix ebook
        run: sh ebook.sh
          
      - name: Create PDF
        uses: docker://pandoc/latex:latest
        with:
          args: >-
            -V
            toc-title:"Table
            Of
            Contents"
            --toc
            --pdf-engine=pdflatex
            -s
            -o
            hacker-laws.pdf
            hacker-laws.md"
          
      - name: Upload created PDF
        uses: actions/upload-artifact@v2
        with:
          name: hacker-laws PDF
          path: hacker-laws.pdf