name: Create PDF ebook
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Copy assets
        run: |
          cp -v ./hacker-laws/README.md README.md
          cp -av ./hacker-laws/images ./images
          
      - name: Create MD for ebook
        run: sh -x ebook.sh
          
      - name: Create PDF
        uses: docker://pandoc/latex:latest
        with:
          args: >- # allows you to break string into multiple lines
            -V
            toc-title:"Table
            Of
            Contents"
            --toc
            --pdf-engine=pdflatex
            -s
            -o
            hacker-laws.pdf
            hacker-laws.md
          
      - name: Upload created PDF
        uses: actions/upload-artifact@v2
        with:
          name: hacker-laws PDF ebook
          path: hacker-laws.pdf